ALTER TABLE raw_materials ADD COLUMN average_cost DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE sales ADD COLUMN total_cogs DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE sale_details ADD COLUMN cogs DECIMAL(15,2) NOT NULL DEFAULT 0.00;
